language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/VEditorKit.xcworkspace -scheme RxCocoa-Texture | xcpretty
- xcodebuild build -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit CODE_SIGNING_REQUIRED=NO | xcpretty
# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage/